# This is a basic workflow to help you get started with Actions
# https://github.com/marketplace/actions/azure-blob-upload
name: Upload To Azure Blob Container
on:
  push:
      branches: [ main ]
jobs:
  upload:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: LanceMcCarthy/Action-AzureBlobUpload@v1.9.0
        with:
          connection_string:  ${{ secrets.TESTCORSDAVE }}
          container_name: 'test-container'
          source_folder: 'Solution Collections'
          destination_folder: ''
          clean_destination_folder: true
